name: santaana
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  oktoast: ^2.1.8
  dio: 2.1.7
  permission: ^0.1.2
  shared_preferences: ^0.5.3+1
  geolocator: ^5.0.0
  location: ^2.3.5
  google_maps_flutter: 0.5.16
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

    

  uses-material-design: true